global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
       - targets:
        #- alertmanager:9093

rule_files:
# - "alert_rules.yml"

scrape_configs:
- job_name: 'Jenkins_Prometheus'
  metrics_path: '/prometheus'
  static_configs:
    - targets: ['54.172.3.54:8080']
