pipeline {
    agent none
    environment {
        REPO_URL = "https://github.com/junaid-13/end-2-end-project.git"
        REPO_NAME = "end-2-end-project"
        GITHUB_TOKEN = credentials('github_token')
    }
    stages {
        stage ('Cloning repository') {
            agent { 
                label 'terraform'
            }
            steps {
               /* sh 'cd infra-deploy/scripts/'
                sh 'chmod +x repo.sh'*/
                sh '''echo "Current working directory: $(pwd)"
                chmod +x scripts/repo.sh
                ./scripts/repo.sh '''
            }
        }
        stage ('Terraform Installation') {
                agent { 
                    label 'terraform'
                }
                steps {
                sh ''' 
                chmod +x scripts/terraform-installation.sh
                ./scripts/terraform-installation.sh '''
            }
        }
        stage ('Deploying infrastructure') {
              agent { 
                    label 'terraform'
                }
            steps {
                sh 'terraform --version'
                sh '''
                echo '*****************************'
                echo 'Initializing Terraform...'
                echo '*****************************'
                '''
                sh '''
                cd GitHub_repository
                echo "Current working directory: $(pwd)"
                terraform init
                echo '*****************************'
                echo 'Validating Terraform configuration...'
                echo '*****************************'
                '''
                sh 'terraform validate'

                sh '''
                echo '*****************************'
                echo 'Planning Terraform configuration...'
                echo '*****************************'
                '''
                retry (2) {
                    sh '''
                    cd GitHub_repository
                    echo "Current working directory: $(pwd)"
                    terraform plan -var GITHUB_TOKEN=$GITHUB_TOKEN_PSW
                    '''
                }
                sh '''
                echo '*****************************'
                echo 'Applying Terraform configuration...'
                echo '*****************************'
                '''
                retry (2) {
                    sh '''
                    cd GitHub_repository 
                    pwd
                    echo $GITHUB_TOKEN
                    terraform apply --auto-approve -var GITHUB_TOKEN=$GITHUB_TOKEN_PSW
                    '''
                }

            }
        }
    }
}
